### ISSUE TITLE
Navigate with dynamic route

### ISSUE THREAD

**Issue by skates008** [bodrovis-learning/Lokalise-source#1]
Hello,
I am having a problem to navigate to another url for dynamic route configured.

Currently i have 
`<router-link v-if="mode===undefined" class="btn btn-primary btn-flat btn-social" tag='a' :to="{ path: url.add}"><i class="fa fa-plus"></i> {{ $t('add') }} </router-link> `
where my url.add is dynamic  for eg for below route is :'university/add'

```
My route is configured as 
{
      path: '/:lang',
      component: {
        template: '<router-view></router-view>'
      },
      beforeEnter: Trans.routeMiddleware,

      children: [
      {
        path: "university",
        component: {
          render(c) {
            return c("router-view");
          }
        },
        meta: { label: "University" },
        children: [
          {
            path: "",
            component: TheContainer,
            children: [
              {
                path: "", name: ":mode", component: load('setup/University'), meta: { requiresAuth: true }
              },

              {
                path: ":mode", component: load('setup/University'), props: true, meta: { requiresAuth: true }
              },
              {
                path: ":mode/:id", name: "", component: load('setup/University'), props: true, meta: { requiresAuth: true }
              }
            ]
          }
        ]
      }...
	  ]
}
```

I have tried($i18nRoute({ path: url.add})) this but it is not working: 
` <router-link v-if="mode===undefined" class="btn btn-primary btn-flat btn-social" tag='a' :to="$i18nRoute({ path: url.add})"><i class="fa fa-plus"></i> {{ $t('add') }} </router-link>`

**Comment by bodrovis** [comment]
I'll try to look into it

**Comment by bouachalazhar** [comment]
I have the same problem in vue3 : 

`path: "/:lang",
    component: {
      render(c) {
        return c("router-view");
      },
    },`

with warnings : 
![image](https://user-images.githubusercontent.com/78004884/191590904-06b494f8-f009-4b0b-b190-1b2c8a254fad.png)

**Comment by bodrovis** [comment]
Unfortunately that guide is not adapted for Vue 3. I was planning to write a new one for quite some time but for now I just don't have much time. Hopefully it'll be addressed soon. In any case, thank you for your feedback!

**Comment by bouachalazhar** [comment]
OK maybe do you have any idea ?

**Comment by bodrovis** [comment]
I would love to help but I haven't checked Vue 3 yet :)
