### ISSUE TITLE
How to hot refresh if key is updated in lokalise

### ISSUE THREAD

**Issue by InCodingNowLiu** [bodrovis-learning/Lokalise-source#2]
How to hot refresh if key is updated in lokalise?

I mean do not donwload the file, just noti website, website will auto refresh this key

**Comment by bodrovis** [comment]
Good day. I don't think that's the best place to discuss such questions, but all in all you're looking for webhooks https://docs.lokalise.com/en/articles/3184756-webhooks Just setup a webhook to notify your website once a key is updated, it's very simple. Then on your website you'll need to somehow open your translation file and modify one of the keys.
